services:
    microsoft_graph.client:
        class: Mbdax\MicrosoftGraphBundle\DependencyInjection\MicrosoftGraphClient
        arguments: ['@request_stack', '@service_container']

    microsoft_graph.request:
        class: Mbdax\MicrosoftGraphBundle\DependencyInjection\MicrosoftGraphRequest
        arguments: ["@microsoft_graph.client"]


    microsoft_graph.redirect_exception_listener:
        class: Mbdax\MicrosoftGraphBundle\EventListener\RedirectExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

            
    # Exemple of Token Storage Manager. You can use it ;-) 
    microsoft_graph.session_storage:
        class: Mbdax\MicrosoftGraphBundle\Token\SessionStorage
        arguments: ["@session", '@service_container']
    
    microsoft_graph.calendar:
        class: Mbdax\MicrosoftGraphBundle\Service\Calendar
        arguments: ["@microsoft_graph.request"]
    
    microsoft_graph.sharepoint:
        class: Mbdax\MicrosoftGraphBundle\Service\SharePoint
        arguments: ["@microsoft_graph.request"]
